# 使用语言为 Node.js
language: node_js
# Node.js 版本，Node 11.0.0 版本 yarn install 会报错不支持 
# node_js: stable
node_js: 10.10.0
# 设置只监听哪个分支 
branches:
  only:
  - hexo
# 缓存，可以节省集成的时间，这里用了 yarn, 如果不用可以删除 
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - CNAME
# env
# 全局变量，为了安全，不要在这里设置，我这里设置只是示例，其实没有用到 
env:
 global:
   - GITHUB_URL: github.com/leungyukshing/leungyukshing.github.io.git
   - CODING_URL: e.coding.net/leungyukshing/leungyukshing/leungyukshing.git
# tarvis 生命周期执行顺序详见官网文档 
before_install:
# 更改时区 
- export TZ='Asia/Shanghai'
- git config --global user.name ${USER_NAME}
- git config --global user.email ${USER_EMAIL}
# 由于使用了 yarn, 所以需要下载，不用 yarn 这两行可以删除 
#- curl -o- -L https://yarnpkg.com/install.sh | bash
#- export PATH=$HOME/.yarn/bin:$PATH
# hexo 基础工具 
- npm install -g hexo-cli
# 初始化所需模块，在 package.json 中配置的有，这样 node_modules 就不用提交到 GitHub 了 
# 下次如果换电脑，安装完 Node.js, 全局 (-g 参数) 安装完 hexo-cli, 直接在项目根目录初始化即可 (在 package.json 配置的都会自动下载)
- npm install
# 本地搜索需要工具 
- npm install hexo-generator-searchdb --save
# 字数统计，时长统计需要工具，Node 版本 7.6.0 之前，请安装 2.x 版本，npm install hexo-wordcount@2 --save
# - npm install hexo-wordcount --save
# 站点地图，seo 优化使用 
- npm install hexo-generator-sitemap --save
- npm install hexo-generator-baidu-sitemap --save
# 中英文之间自动增加空格插件 
# - npm install hexo-filter-auto-spacing --save (这个人用的少，不用了)
- npm install hexo-pangu-spacing --save
# rss 订阅插件 
- npm install hexo-generator-feed --save
# 三维卡通人物 
# - npm install --save hexo-helper-live2d
# 三维卡通人物 - 小猫咪模型下载 (保险起见，把模型文件放到自己的文件夹里，不用每次下载)
# - npm install --save live2d-widget-model-hijiki
# 压缩文件 
- npm install hexo-neat --save
install:
# 不用 yarn 的话这里改成 npm i 即可 
- npm install
script:
- hexo clean
- hexo generate
# 成功之后才会提交，如果失败就会跳过并发送失败邮件通知 
after_success:
# 获取 master 分支内容 
- git clone https://${GITHUB_URL} .deploy_git
- cd .deploy_git
- git checkout master
- cp -rf ../public/* ./
# 必要配置文件 
- cp -rf ../README.md ../.gitignore ../CNAME ../index.php ./
# 更改 .gitignore 内容，与 source 分支的不一样，直接置空，目前没有需要过滤的 
- echo "" > ./.gitignore
- git add .
# 提交记录包含时间，跟上面更改时区配合 
- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
# 推送到主分支 
- git push --force --quiet "https://${REPO_TOKEN}@${GITHUB_URL}" master:master
- git push --force --quiet "https://leungyukshing:${CO_TOKEN}@{CODING_URL}" master:master
# 邮件通知机制，我在这里设置了成功 / 失败都会通知，这里不能使用环境变量 
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - jacky14.liang@gmail.com
  on_success: always
  on_failure: always
